### ISSUE TITLE
Kickoff: Project Structure?

### ISSUE THREAD

**Issue by taurean** [tatianamac/devsofcolour#1]
I talked briefly with @kaesve about building this as a simple one-pager app that looped through data in a `.JSON` file also in this repo's directory and he said that would be the simplest route provided we can load the whole file at once which sounds do-able. Where's the best place to start?

Some questions off the top of my head:
* Does anyone have a preference on what to use to build this? (would help to set up initial scaffolding)
* what information do we want to display for each profile? 
* It looks like [womenwhodesign](http://womenwho.design), [blackswhodesign](https://blackswho.design), [latinxwhodesign](http://latinxswho.design), etc all use a similar layout. Is this something we should put an effort into emulating? 
* are there any design/technical limitations we should be taking into consideration early on?

**Comment by tatianamac** [comment]
I've been out of the country for the last few weeks and just getting back into a flow.

@taurean @kaesve I am chatting with an OSS contributor who has been conducting research around databases like this (including the ones you mentioned, @taurean ). I can update you all after that call (which will happen in Monday).

My initial thoughts are:

- I don't necessarily have a preference as to what we use to build it as long as it doesn't present major a11y issues from the onset (as some frameworks are more difficult to make accessible, I'm finding).
- That the framework minimises the need for the user to know a specific language (unless it's a more agnostic one, like markup).
- While I understand the layouts and precedent set with those databases, I'd love to challenge/research if that's the best layout (something I'll be discussing with the researcher on the call).

**Technical limitations for me are:**
- How are we making this most accessible/easiest to upload to? 
- How can we make this easiest to sort (given that the goal of this is to connect hireable devs with employers) by language, areas of focus (like a11y, performance, etc)?
- What are our vetting processes? With something like 'of colour' as a criterion, we have to rely on the honour system. Essentially, we have to ask the user to sign a contract of sorts that they are promising that they identify as a person of colour.
- What kind of updates will we allow in the future? How do we facilitate them (say, if someone wants to change something on their profile)? Pull requests?

Initial thoughts there for framing. What do you all think?

**Comment by taurean** [comment]
👋 Welcome back, hopefully it was a good trip!

I was thinking more about how people might manage their information and I'm now curious if we can maybe get something to work with google sheets. This would allow people who maybe aren't familiar with git or don't even have GitHub accounts to still add/manage/remove their information. 

- I 100% share the same vision/values/goals with regard to how this should be accessible to people both from maintaining their data as well as technical accessibility with how the site is built. 
- regarding framework, I don't have strong opinions on this but I've had some good experiences working inside a Vue project so maybe that? I'm open to whatever. 
- I also agree with regard to the vetting process though I'd like to hear more about your thoughts on what a contract would look like. I'd like to assume an honor system will be enough but it's worth considering how we can also protect this project from abuse. 
- Another thing we'll have to keep in mind with how data is recorded is GDPR compliance, I'm assuming this will be an international resource (which might provide challenges also)

looking forward to hearing what you learn from the call on Monday and can't wait to get started 😄

**Comment by tatianamac** [comment]
Hi! I had an awesome chat with someone who is working to build something similar, which was insightful. Some things I want to document/responses to what you wrote.

- I have really nonexistent JS knowledge, so if we need a JS framework, I'll defer to y'all who will be building that portion of that.
- Re: vetting, I think it has to be an agreement of some sort that basically says "I'm acknowledging that I identify as a person of colour" and don't benefit from the safety of whiteness.
- Yes, good point about GDPR. We'll have to look into that and what that means—Yankees. :) Storing data/contact info is probably the most pertinent thing.
- I love the idea of Google Sheets except I'm very very weary about tethering anything so squarely to Google. Do we feel providing markup/Github is too technically restrictive to most devs?
- Layout-wise, I'd like to consider a model beyond the current status quo. I'm curious if there's a way to prioritise what the person does. While the avatar is nice from a humanisation standpoint, it's quite a bit of real estate for something that ultimately shouldn't factor into the person's decision to collaborate? Instead, it'd be cool to make a datavis of what languages they code in, or where they're from. Something data-driven?

**Questions**

- Re: GDPR: I imagine we want to avoid storing any sensitive information like email addresses. It may make more sense to connect people to somewhere else to contact them (i.e., GitHub or their personal website).
- Is connecting through GitHub or using the GitHub API beneficial at all? That way, people could see code examples/languages, etc?
- How robust can we make search? Part of what I discussed on my call was how most directories are really shallow, which makes them not very helpful to find meaningful people. I'd love to start setting what we think the key terms are (languages, frameworks, orthogonal specialties (like a11y, performance))
- Also, narrowing the scope or intent might be helpful. What is the goal of this particular directory? Job seeking and matching? There can be secondary use cases, but I think it's important to define a primary.
- I thought about how it would be helpful to indicate how "active" somebody is so that the most active individuals are the ones prioritised/listed in the search? If someone is inactive for a certain amount of time, it might make sense to set their account to inactive (which they can revive later). It does beg the question as to what "active means.
- Should we set a cap, as a result? Is this system one that can scale forever?

Anyway, that's probably enough thoughts for now. Also, should we start breaking this up into multiple issues so we can start agreeing upon/defining frameworks?

Also I added my pal and talented designer and dev @andybelldesign as he and I have discussed collaborating as well!

**Comment by Andy-set-studio** [comment]
Hey folks! I have been _deep_ in getting a thing ready for release, but I’ve bobbed my head over the trenches to give this a look 🙂

Here's some responses:

## Vetting
I'm with Tatiana on this. It’s gotta be a trust thing or we could be in real danger of creating a hostile, unhelpful environment.

## Data
When I had the initial chat with Tatiana, I suggested a similar approach to how I run [personal sites](https://github.com/hankchizljaw/personalsit.es#add-your-site). If we keep content static and open I think it'll help build trust with folks and also help us on a GDPR front. The key with GDPR is users should be able to request that information is removed that identifies them. In an open, transparent setup, it'll be a case of them opening a PR. That gives us an audit trail for free, too.

Leveraging something like Eleventy for the site itself gives us lots of flexibility, too as it has zero opinions! We could build it however we wanted.

If we go for a proper database, I think we'll encounter problems such as who owns the data? Who is responsible and has liability? Those sort of things can cause a lot of friction in what should be a very nice project IMO.

Anyway, I’m really glad these discussions are happening :)

**Comment by taurean** [comment]
Sorry for the radio silence, I get back from a trip tomorrow (@kaesve’s wedding actually! 🎉). I’ll try to give a more useful response on Thurs/Friday.

**Comment by Andy-set-studio** [comment]
No rush at all @taurean!

**Comment by taurean** [comment]
@andybelldesign wrt keeping things static, do you mean just maintaining a static HTML file and let people edit that to add/update/remove their information? I agree that a proper database might be difficult to manage. 

@tatianamac wrt the agreement:
> "I'm acknowledging that I identify as a person of colour" and don't benefit from the safety of whiteness.

If we take this route, we might be forcing some people to self-select themselves out of being included since being a person of color and benefiting from whiteness aren't mutually exclusive. With that said, that isn't necessarily a bad thing. One issue I don't know how to design around is making sure companies don't cherrypick candidates who are white passing or otherwise "palatable" in their eyes. 

We should also maybe take stock of the different skillsets we need to get to something shippable. Right now theres a lot of overlap, I'm curious if there are any things we need that we can't pull off ourselves right now.

**Comment by Andy-set-studio** [comment]
> wrt keeping things static, do you mean just maintaining a static HTML file and let people edit that to add/update/remove their information? I agree that a proper database might be difficult to manage.

I reckon we go with something like 11ty.io, @taurean, so folks can PR single `.md` files. I think a massive HTML page could be super intimidating, although I would _love_ a dependency free setup.

**Comment by tatianamac** [comment]
Good point @taurean. It’s going to come down to exact wording (which what I wrote is not nearly to where it needs to be), which I’ll want to vet with the most marginalised folks of colour.

I like that we’re thinking of dependency. I feel like markdown is most accessible and easiest to explain via placeholder, personally.

Future plans we can find ways to maybe use Hylia (Andy’s dope project) to help folks “upgrade” their profiles. 🤗

**Comment by Andy-set-studio** [comment]
That project’s whole backbone is helping folks get their own voice online, so it makes sense to try and incorporate it.

**Comment by tatianamac** [comment]
Motion to close this kickoff issue and capture any issues from it as singular issues to better discuss and to track:

- Start instance of 11ty for site? (@andybelldesign ?)
- Create components in Figma for review (@tatianamac )

What else?

**Comment by Andy-set-studio** [comment]
Agreed. I'm just in the process of creating a version of Hylia that is just HTML. Once I get that going, I'll do a PR into here with our starting point. Sound good?

**Comment by taurean** [comment]
Sounds good to me!
