### ISSUE TITLE
profile information

### ISSUE THREAD

**Issue by taurean** [tatianamac/devsofcolour#2]
What information should we include when presenting each profile? Should we have optional fields? If we go the route of just editing an HTML file we should create a separate example of the markup either in a readme or in the file itself. Unrelated but it'd be great if we can randomize the order of profiles without messing up the tab ordering.

**Comment by Andy-set-studio** [comment]
If we go down the 11ty route, like I mentioned in #1, we could structure markdown files like this: 

```markdown
---
name: 'Person Name'
url: 'https://example.com'
tags: ['designer', 'writer']
twitter: '@handle'
github: 'username'
pronouns: 'they/them'
---
```

**Comment by Andy-set-studio** [comment]
I totally agree there should be optional fields!

**Comment by taurean** [comment]
I somehow totally missed the 11ty mention, I love this

**Comment by Andy-set-studio** [comment]
It's super good. It'll totally separate data/content from the code which should make it easier to contribute _and_ make everything totally transparent 🙂

**Comment by Andy-set-studio** [comment]
I just spotted this from @tatianamac pop up in my Twitter feed. There’s loads of replies and it looks like we have our structure too! https://twitter.com/TatianaTMac/status/1135997092432830464

**Comment by taurean** [comment]
Looks like a great baseline to me! I like the addition you had of pronouns and it would be great to include "looking for a mentor/looking _to_ mentor", as well as current employer and if you're looking for work and/or wish to be contacted.

**Comment by Andy-set-studio** [comment]
I think we could give guidance for tags for some of that stuff. That'd help us make filter pages for folks too.

**Comment by tatianamac** [comment]
I would love to add:

Languages (human)
Languages (programmatic)
Specialties/Focus (a11y, webperf, inclusive design, creative coding, community building)

I would like to add on levels to work somehow, like:

Urgently/actively/casually searching (FTE, contract) so we can sort by/prioritise folks that say need to pay rent ASAP, for example. 

Urgently/actively/casually hiring? This one is more complex to me but worth it for folks looking to place? Or maybe more simply a one line “Hiring [text field]

With regards to requires fields, I think having to include name (but having it accept all name types) and maybe requiring at least one of twitter, Github, or website (since there needs to be some way to get a hold of you).

**Comment by taurean** [comment]
loving the sound of all of this (especially prioritizing certain folks). I'm not familiar with Hylia or 11ty. How quickly could we maybe whip up a proof of concept using those tools? 

Also, should we do bio's as an option as well? These profiles might feel kind of stale as they're just sets of lists in it's current state. Maybe that's a good thing though?

**Comment by tatianamac** [comment]
I like the idea of getting away from headshots, because that in a weird way perpetuates some of the issues we're trying to get away from. It's become the defacto pattern for databases like this.

Something I love about Codepen is the deemphasis on the person and the emphasis on something visual. Understanding that not everyone's work is visual, we could have that be a toggle-able (toggled?) option (for viewing and listed users). Or, we could let folks styling some text or something (to make typography visual).

I struggle with SSGs, so I'll have to rely on y'all to help me here. I know Andy is a wizard at getting these sites spinned up super quickly. I'll defer to him on this approach.

I'd be happy to build a little Codepen or something with the type of pattern I'm thinking of.

**Comment by taurean** [comment]
Yeah that'd be great! Especially useful since you can fork codepens to brainstorm without losing work.

**Comment by Andy-set-studio** [comment]
> Urgently/actively/casually searching (FTE, contract) so we can sort by/prioritise folks that say need to pay rent ASAP, for example.

Just gonna mention that I see an abuse risk with this one. Abuse in that folks could drown out others genuine need with their own selfish need of this feature.

***

I think little CodePen prototypes will be ideal at this point. We can keep discussing them within the threads on here then, too 🙂

**Comment by tatianamac** [comment]
@andybelldesign Do you think there's value in allowing that sort at all? Is it the levels that you worry about?

Also, perfect! I'm slammed this week with a launch but should have more time next week.

**Comment by Andy-set-studio** [comment]
Good point. It's the people that value themselves higher than others that I worry about. Y'know the type: folks who will park in a disabled spot because "they're in a rush"

**Comment by tatianamac** [comment]
To give a pass at structuring content so we can start building _something_

```markdown
---
name: 'Person Name' _required_
url: 'https://example.com' _required_ (But we can kindly suggest many options?)
work tags: ['designer', 'writer', 'community organiser'] feels like we should require at least one? But open here
identifier tags: ['LGBTQIA+, PoC, disabled] stress on completely optional
seeking tags: I see this as a dual thing: ['mentor', 'contractor'] seeking ['protege', 'contract work']
languages (human): ['English', 'Igbo', 'Hindi', 'Spanish', etc]
languages (computer): ['HTML', 'CSS', 'Python', 'Ruby', 'Rust', 'JS', etc]
codepen: 'username' 
twitter: '@handle'
github: 'username' 
pronouns: 'they/them' 
```

**Comment by Andy-set-studio** [comment]
I love this. We might have to structure the seeking like this: 

```
seeking_as: ['mentor', 'contractor']
seeking: ['protege', 'contract work']
```

**Comment by tatianamac** [comment]
Would it be helpful if I changed this into a project so we can track/assign individual tasks?

**Comment by Andy-set-studio** [comment]
Hell yeh

**Comment by taurean** [comment]
decided to mess around with possible profile designs before bed, extreme rough draft: https://codepen.io/taurean/pen/eqJOVy?editors=1100

definitely needs more work (didn't even feel like adding icons for social media for example). Might be a good starting point but totally fine scrapping if either of you had something else in mind.
